export const GET_MEDICINES = 'GET_MEDICINES';
export const GET_MEDICINE = 'GET_MEDICINE';
export const ADD_MEDICINE = 'ADD_MEDICINE';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const MEDICINES_LOADING = 'MEDICINES_LOADING';
